import React, { useEffect, useState } from 'react';
import { Plus, Search, Edit2, Archive, Tag, X, Save } from 'lucide-react';
import type { AdminCoupon } from '../../types/admin';

export default function AdminCoupons() {
  const [coupons,setCoupons]=useState<AdminCoupon[]>([]); const [loading,setLoading]=useState(true); const [searchQuery,setSearchQuery]=useState('');
  const [editing,setEditing]=useState<any|null>(null); const [form,setForm]=useState({code:'',type:'PERCENTAGE',value:10,minOrder:0,maxDiscount:'',usageLimit:'',active:true}); const [saving,setSaving]=useState(false);
  const load=()=>fetch('/api/admin/coupons').then(r=>r.json()).then(setCoupons).finally(()=>setLoading(false)); useEffect(()=>{load().catch(console.error)},[]);
  const openCreate=()=>{setEditing({id:null});setForm({code:'',type:'PERCENTAGE',value:10,minOrder:0,maxDiscount:'',usageLimit:'',active:true})};
  const openEdit=(c:any)=>{setEditing(c);setForm({code:c.code||'',type:c.type||'PERCENTAGE',value:Number(c.value||0),minOrder:Number(c.minOrder||0),maxDiscount:c.maxDiscount??'',usageLimit:c.usageLimit??'',active:c.active!==false})};
  const save=async(e:React.FormEvent)=>{e.preventDefault();setSaving(true);try{const r=await fetch(editing?.id?`/api/admin/coupons/${editing.id}`:'/api/admin/coupons',{method:editing?.id?'PUT':'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify(form)});if(!r.ok)throw new Error((await r.json()).error||'Save failed');setEditing(null);await load()}catch(e){alert(e instanceof Error?e.message:'Save failed')}finally{setSaving(false)}};
  const archive=async(id:string)=>{if(!confirm('Deactivate this coupon?'))return;await fetch(`/api/admin/coupons/${id}`,{method:'DELETE'});await load()};
  const filtered=coupons.filter(c=>c.code.toLowerCase().includes(searchQuery.toLowerCase()));
  return <div><div className="flex justify-between items-center mb-8"><div><h1 className="font-display text-2xl font-bold text-charcoal">Coupons</h1><p className="text-gray-500 text-sm mt-1">Manage discount codes and promotions.</p></div><button onClick={openCreate} className="bg-charcoal text-white px-4 py-2 rounded-lg text-sm font-medium flex items-center gap-2"><Plus size={16}/>Create Coupon</button></div>
  {editing&&<form onSubmit={save} className="bg-white border rounded-xl p-5 mb-6 grid md:grid-cols-4 gap-3"><input required placeholder="CODE" value={form.code} onChange={e=>setForm({...form,code:e.target.value.toUpperCase()})} className="px-3 py-2 bg-gray-50 border rounded-lg text-sm"/><select value={form.type} onChange={e=>setForm({...form,type:e.target.value})} className="px-3 py-2 bg-gray-50 border rounded-lg text-sm"><option value="PERCENTAGE">Percentage</option><option value="FIXED">Fixed</option><option value="FREE_SHIPPING">Free Shipping</option></select><input type="number" min="0" value={form.value} onChange={e=>setForm({...form,value:Number(e.target.value)})} placeholder="Value" className="px-3 py-2 bg-gray-50 border rounded-lg text-sm"/><input type="number" min="0" value={form.minOrder} onChange={e=>setForm({...form,minOrder:Number(e.target.value)})} placeholder="Min order" className="px-3 py-2 bg-gray-50 border rounded-lg text-sm"/><input type="number" min="0" value={form.maxDiscount} onChange={e=>setForm({...form,maxDiscount:e.target.value})} placeholder="Max discount" className="px-3 py-2 bg-gray-50 border rounded-lg text-sm"/><input type="number" min="1" value={form.usageLimit} onChange={e=>setForm({...form,usageLimit:e.target.value})} placeholder="Usage limit" className="px-3 py-2 bg-gray-50 border rounded-lg text-sm"/><label className="flex items-center gap-2 text-sm"><input type="checkbox" checked={form.active} onChange={e=>setForm({...form,active:e.target.checked})}/>Active</label><div className="flex gap-2"><button disabled={saving} className="flex-1 bg-charcoal text-white rounded-lg"><Save size={15} className="inline mr-1"/>{saving?'Saving':'Save'}</button><button type="button" onClick={()=>setEditing(null)} className="px-3 border rounded-lg"><X size={15}/></button></div></form>}
  <div className="bg-white border rounded-xl overflow-hidden"><div className="p-4 border-b"><div className="relative"><Search className="absolute left-3 top-1/2 -translate-y-1/2 text-gray-400" size={18}/><input placeholder="Search coupons..." className="w-full pl-10 pr-4 py-2 bg-gray-50 border rounded-lg text-sm" value={searchQuery} onChange={e=>setSearchQuery(e.target.value)}/></div></div><div className="overflow-x-auto"><table className="w-full text-left text-sm"><thead className="bg-gray-50 text-gray-500 border-b"><tr><th className="px-6 py-3">Code</th><th className="px-6 py-3">Discount</th><th className="px-6 py-3">Usage Limit</th><th className="px-6 py-3">Used</th><th className="px-6 py-3">Status</th><th className="px-6 py-3 text-right">Actions</th></tr></thead><tbody className="divide-y">{loading?<tr><td colSpan={6} className="px-6 py-8 text-center">Loading...</td></tr>:filtered.map(c=><tr key={c.id}><td className="px-6 py-4 font-medium"><Tag size={14} className="inline mr-2 text-gray-400"/>{c.code}</td><td className="px-6 py-4 text-gray-500">{c.type==='PERCENTAGE'?`${c.value}%`:c.type==='FREE_SHIPPING'?'Free shipping':`₹${c.value}`}</td><td className="px-6 py-4 text-gray-500">{c.usageLimit||'Unlimited'}</td><td className="px-6 py-4 text-gray-500">{c.usageCount}</td><td className="px-6 py-4">{c.active?'Active':'Inactive'}</td><td className="px-6 py-4 text-right"><button onClick={()=>openEdit(c)} className="p-2"><Edit2 size={16}/></button><button onClick={()=>archive(c.id)} className="p-2 text-red-500"><Archive size={16}/></button></td></tr>)}</tbody></table></div></div></div>;
}
